# Generated by Django 5.1.3 on 2025-03-30 02:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('calculation_method', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InputField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('telephone', 'Telephone'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('number', 'Number'), ('email', 'Email'), ('date', 'Date'), ('file', 'File')], max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('max_characters', models.IntegerField(blank=True, null=True)),
                ('min_characters', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='WaqfProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Project', max_length=255)),
                ('domain', models.CharField(default='General', max_length=255)),
                ('objectives', models.TextField(default='No objectives specified')),
                ('partners', models.TextField(default='No partners specified')),
                ('image', models.ImageField(blank=True, null=True, upload_to='waqf_images/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZakatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zakat_base', models.FloatField(default=0.0)),
                ('zakat_result', models.FloatField(default=0.0)),
                ('month_type', models.CharField(default='Unknown', max_length=50)),
                ('calculation_date', models.DateField(default=django.utils.timezone.now)),
                ('nissab', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='api.companytype')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
