# Generated by Django 5.1.7 on 2025-03-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfield',
            name='label',
            field=models.CharField(default='Default Label', max_length=255),
        ),
        migrations.AlterField(
            model_name='companyfield',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
