# Generated by Django 5.1.7 on 2025-03-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_companyfield_label_alter_companyfield_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfield',
            name='label',
            field=models.CharField(max_length=255),
        ),
    ]
