# Generated by Django 5.1.7 on 2025-04-30 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_zakathistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfield',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.companyfield'),
        ),
    ]
