# Generated by Django 5.1.2 on 2025-10-05 18:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_companyfield_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ma7acil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zakat_amount', models.FloatField(default=0.0)),
                ('total_amount', models.FloatField(default=0.0)),
                ('corp_type', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ma7acil_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ma7acil',
            },
        ),
    ]
